(() => {
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const host=document.getElementById('workspacePayments');if(!host)return;
 let loaded=false,busy=false,channels=[],receipts=[],error='',generation=0,receiptFilter='pending';
 PAGE_NAMES.payments='收款码与审核';document.querySelectorAll('[data-page="sales"]').forEach(el=>{const b=el.cloneNode(true);b.dataset.page='payments';b.innerHTML='<span class="navIcon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/></svg></span><span class="navText"><b>收款码与审核</b><small>Payments</small></span>';b.onclick=()=>setPage('payments');el.after(b);});
 const dialog=document.createElement('dialog');dialog.addEventListener('cancel',e=>{if(dialog.querySelector('[data-close]')?.disabled)e.preventDefault();});dialog.className='auction-dialog payment-dialog payment-admin-dialog';document.body.append(dialog);
 function shell(title,html){dialog.innerHTML=`<button data-close>关闭 ×</button><h2>${title}</h2>${html}`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();}
 async function call(name,args){const r=await sb.rpc(name,args);if(r.error)throw r.error;return r.data;}
 async function signed(path){const r=await sb.storage.from('payment-media').createSignedUrl(path,300);if(r.error)throw r.error;return r.data.signedUrl;}
 async function load(){if(!currentUser||!canWrite())return;const own=++generation;busy=true;error='';try{const results=await Promise.all([sb.from('payment_channels').select('*'),window.SuohaData.fetchAll(sb,'payment_receipts',[['created_at',false],['id',true]])]);for(const r of results)if(r.error)throw r.error;if(own!==generation)return;channels=results[0].data;receipts=results[1].data;loaded=true;}catch(e){if(own===generation)error='读取失败：'+e.message+'（请确认已执行 030 至 034 的付款相关迁移）';}finally{if(own===generation){busy=false;render();}}}
 const amountText=r=>r.amount_ocr_status==='recognized'&&r.recognized_amount!=null?'¥'+Number(r.recognized_amount).toFixed(2):({no_image:'未上传截图',not_detected:'未识别到金额',failed:'金额识别失败',legacy:'历史记录，需核实'})[r.amount_ocr_status]||'历史记录，需核实';
 function render(){if(state.page!=='payments')return;if(!canWrite()){host.textContent='仅授权编辑成员可管理收款。';return;}const visible=receipts.filter(r=>receiptFilter==='all'||r.status===receiptFilter);host.innerHTML=`<div class="ws-heading"><div><h1>收款审核</h1><p>先处理待审核付款，再进入意向与销售安排交付。截图金额由服务端识别，到账仍需核实。</p></div><button class="ws-action" data-refresh ${busy?'disabled':''}>刷新</button></div>${error?`<p role="alert">${esc(error)}</p>`:''}<section class="ws-panel"><h2>付款记录</h2><div class="ws-tabs">${[['pending','待审核'],['confirmed','已确认'],['rejected','已退回'],['all','全部']].map(([key,label])=>`<button data-receipt-filter="${key}" class="${receiptFilter===key?'active':''}">${label}</button>`).join('')}</div><p>待审核 ${receipts.filter(r=>r.status==='pending').length} 条。可切换分类查看历史记录；已核实订单继续在“意向与销售”处理交付。</p>${visible.length?`<div class="ws-table-wrap"><table class="ws-table"><thead><tr><th>订单</th><th>付款信息</th><th>OCR / 状态</th><th>操作</th></tr></thead><tbody>${[...visible].sort((a,b)=>(b.status==='pending')-(a.status==='pending')).map(r=>{const order=window.SuohaWorkspace.snapshot().inquiries?.find(i=>i.id===r.inquiry_id);return `<tr><td>${esc(order?.reference||r.inquiry_id)}<small>${new Date(r.created_at).toLocaleString('zh-CN')}</small></td><td>${esc(amountText(r))} · ${esc(r.channel_snapshot.label)}<small>${esc(r.submitted_fields.transaction||'未填写单号')}</small></td><td>${r.screenshot_path?'有截图':'手动填写'} · ${({pending:'待人工确认',confirmed:'已确认到账',rejected:'已退回'})[r.status]}</td><td><button class="ws-action" data-review="${r.id}">查看 / 审核</button></td></tr>`;}).join('')}</tbody></table></div>`:'<p class="payment-empty">当前分类没有付款记录。</p>'}</section><details class="ws-panel payment-settings"><summary>收款方式设置 <small>微信 / 支付宝 / 收款码</small></summary><p>方式一：添加店铺微信后转账。方式二：直接通过收款码付款。联系方式仅向订单买家展示。</p><div class="ws-actions">${[['wechat_transfer','加微信转账'],['wechat','微信收款码'],['alipay','支付宝收款码'],['other','其他收款码']].map(([id,label])=>`<button class="ws-action" data-channel="${id}">${label} · ${channels.find(c=>c.id===id)?.enabled?'已启用':'未启用'}</button>`).join('')}</div></details>`;if(!loaded&&!busy&&!error)load();}
 async function configure(id){const c=channels.find(c=>c.id===id)||{id,label:({wechat_transfer:'加微信转账',wechat:'微信',alipay:'支付宝',other:'其他收款'})[id],payee:'',instructions:'',enabled:false};shell(id==='wechat_transfer'?'配置微信转账':'配置收款码',`<form class="auction-form"><label>显示名称<input name="label" maxlength="60" required value="${esc(c.label)}"></label><label>收款人 / 商户名称<input name="payee" maxlength="100" required value="${esc(c.payee)}"></label><label>付款说明<textarea name="instructions" maxlength="1000">${esc(c.instructions)}</textarea></label>${c.qr_path?'<img data-qr class="payment-qr" alt="当前收款码">':''}${id==='wechat_transfer'?`<label>店铺微信号<input name="wechat_id" maxlength="100" required value="${esc(c.wechat_id||'')}"></label>`:`<label>上传收款码（JPG / PNG / WebP）<input name="image" type="file" accept="image/jpeg,image/png,image/webp" ${c.qr_path?'':'required'}></label>`}<label class="auction-consent"><input name="enabled" type="checkbox" ${c.enabled?'checked':''}>启用此收款方式</label><p role="status"></p><button type="submit" class="ws-action primary">保存收款设置</button></form>`);const f=dialog.querySelector('form');if(c.qr_path)signed(c.qr_path).then(url=>{if(f.isConnected)f.querySelector('[data-qr]').src=url;}).catch(e=>f.querySelector('[role=status]').textContent=e.message);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;try{const session=await sb.auth.getSession();const image=f.elements.image?.files[0]?await window.SuohaPaymentOCR.prepare(f.elements.image.files[0]):null;const r=await fetch('/.netlify/functions/manual-payment',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+session.data.session.access_token},body:JSON.stringify({action:'save_channel',id,label:f.elements.label.value,payee:f.elements.payee.value,instructions:f.elements.instructions.value,enabled:f.elements.enabled.checked,path:c.qr_path,wechat_id:f.elements.wechat_id?.value||null,image})});const result=await r.json();if(!r.ok)throw Error(result.error);dialog.close();await load();}catch(err){f.querySelector('[role=status]').textContent=err.message;}finally{b.disabled=false;}};}
 async function review(id){
  const r=receipts.find(r=>r.id===id);if(!r)return;shell('付款审核','<p>正在读取…</p>');
  try{
   const [url,orderResult]=await Promise.all([r.screenshot_path?signed(r.screenshot_path):Promise.resolve(null),sb.from('purchase_inquiries').select('reference,agreed_price,currency,status,customer_name').eq('id',r.inquiry_id).single()]);
   if(orderResult.error)throw orderResult.error;const o=orderResult.data,known=r.amount_ocr_status==='recognized'&&r.recognized_amount!=null,mismatch=known&&Number(r.recognized_amount)!==Number(o.agreed_price),fields=r.submitted_fields||{};
   const rows=[['支付单号',fields.transaction],['付款时间',fields.time],['买家填写的收款人',fields.payee],['店铺收款配置',r.channel_snapshot.label+' / '+r.channel_snapshot.payee]];
   let html='<p>'+esc(o.reference)+' · '+esc(o.customer_name)+'</p><div class="payment-amounts"><div>订单应付<strong>¥'+esc(o.agreed_price)+'</strong></div><div>截图识别金额<strong>'+esc(amountText(r))+'</strong></div></div>';
   html+=mismatch?'<p role="alert">截图金额与订单应付金额不一致，请重点核实。</p>':!known?'<p role="alert">没有可用的截图金额，请按支付单号在真实收款账户核实。</p>':'<p>截图金额与订单一致，确认前仍需核实真实到账。</p>';
   html+='<div class="payment-review-grid"><section class="payment-evidence">'+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener">打开完整截图</a><img class="payment-preview" src="'+esc(url)+'" alt="买家付款截图">':'<h3>手动提交</h3><p>买家未上传截图，请按右侧支付单号核实。</p>')+'</section><section><dl class="payment-facts">'+rows.map(([label,value])=>'<div><dt>'+label+'</dt><dd>'+esc(value||'未填写')+'</dd></div>').join('')+'</dl><p>审核状态：'+esc(({pending:'待审核',confirmed:'已确认到账',rejected:'已退回'})[r.status])+'</p>'+(r.review_note?'<p>备注：'+esc(r.review_note)+'</p>':'');
   if(r.status==='pending')html+='<form class="auction-form"><label>实际确认到账金额（元）<input name="amount" type="number" min="0.01" step="0.01" required></label><label>审核备注 / 退回原因<textarea name="note" maxlength="1500" placeholder="确认时选填，退回时必填"></textarea></label><button type="button" data-reject-template>填入“请补充账单截图”</button><label class="auction-consent"><input name="verified" type="checkbox">我已在真实收款账户核对收款人、交易单号及足额到账</label><p role="status"></p><div class="ws-actions"><button type="submit" class="ws-action primary" name="decision" value="confirmed">确认实际到账</button><button type="submit" class="ws-action" name="decision" value="rejected" formnovalidate>退回补充</button></div></form>';
   html+='</section></div><details><summary>识别记录（仅辅助核对）</summary><p>金额来源：'+(r.amount_ocr_status==='legacy'?'历史买家端记录':'服务端截图识别')+'</p><pre>'+esc(r.ocr_text||'无识别记录')+'</pre></details>';
   shell('付款审核',html);const f=dialog.querySelector('form');
   if(f){
    f.querySelector('[data-reject-template]').onclick=()=>{f.elements.note.value='请点击账单中本次支付记录并截图，上传包含订单号/转账单号的支付记录截图。';};
    f.onsubmit=async e=>{
     e.preventDefault();const decision=e.submitter.value;
     if(decision==='confirmed'&&!f.elements.verified.checked){f.querySelector('[role=status]').textContent='请先核实真实到账并勾选确认。';return;}
     if(decision==='rejected'&&!f.elements.note.value.trim()){f.querySelector('[role=status]').textContent='请填写退回原因，也可使用上方快捷说明。';return;}
     f.querySelectorAll('button').forEach(b=>b.disabled=true);dialog.querySelector('[data-close]').disabled=true;
     try{await call('review_payment_receipt',{p_id:id,p_decision:decision,p_note:f.elements.note.value,p_amount:f.elements.amount.value?Number(f.elements.amount.value):null,p_verified:f.elements.verified.checked});dialog.close();await load();window.dispatchEvent(new Event('suoha:payment-reviewed'));toast(decision==='confirmed'?'已确认收款，可在意向与销售处理交付':'已退回，买家可重新提交');}
     catch(err){f.querySelector('[role=status]').textContent=err.message;}
     finally{f.querySelectorAll('button').forEach(b=>b.disabled=false);const close=dialog.querySelector('[data-close]');if(close)close.disabled=false;}
    };
   }
  }catch(err){shell('读取失败','<p role="alert">'+esc(err.message)+'</p>');}
 }
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.receiptFilter){receiptFilter=b.dataset.receiptFilter;render();return;}if(b.hasAttribute('data-refresh'))load();if(b.dataset.channel)configure(b.dataset.channel);if(b.dataset.review)review(b.dataset.review);});
 window.addEventListener('suoha:payment-reviewed',()=>window.SuohaWorkspace.load(true));
 window.SuohaPaymentAdmin={render};window.addEventListener('suoha:logout',()=>{generation++;receiptFilter='pending';loaded=false;busy=false;channels=[];receipts=[];error='';host.innerHTML='';dialog.close();});
 if(location.hash==='#payments')setPage('payments',false);
})();
