(() => {
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const host=document.getElementById('workspacePayments');if(!host)return;
 let loaded=false,busy=false,channels=[],receipts=[],error='',generation=0;
 PAGE_NAMES.payments='收款码与审核';document.querySelectorAll('[data-page="sales"]').forEach(el=>{const b=el.cloneNode(true);b.dataset.page='payments';b.innerHTML='<span class="navText"><b>收款码与审核</b><small>Payments</small></span>';b.onclick=()=>setPage('payments');el.after(b);});
 const dialog=document.createElement('dialog');dialog.className='auction-dialog payment-dialog';document.body.append(dialog);
 function shell(title,html){dialog.innerHTML=`<button data-close>关闭 ×</button><h2>${title}</h2>${html}`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();}
 async function call(name,args){const r=await sb.rpc(name,args);if(r.error)throw r.error;return r.data;}
 async function signed(path){const r=await sb.storage.from('payment-media').createSignedUrl(path,300);if(r.error)throw r.error;return r.data.signedUrl;}
 async function load(){if(!currentUser||!canWrite())return;const own=++generation;busy=true;error='';try{const results=await Promise.all([sb.from('payment_channels').select('*'),window.SuohaData.fetchAll(sb,'payment_receipts',[['created_at',false],['id',true]])]);for(const r of results)if(r.error)throw r.error;if(own!==generation)return;channels=results[0].data;receipts=results[1].data;loaded=true;}catch(e){if(own===generation)error='读取失败：'+e.message+'（请确认已执行 030_manual_payments.sql 和 031_wechat_transfer.sql）';}finally{if(own===generation){busy=false;render();}}}
 function render(){if(state.page!=='payments')return;if(!canWrite()){host.textContent='仅授权编辑成员可管理收款。';return;}host.innerHTML=`<div class="ws-heading"><div><h1>收款码与人工审核</h1><p>OCR 仅提取截图信息。确认前请打开真实收款账户核对交易单号、收款人和金额。</p></div><button class="ws-action" data-refresh ${busy?'disabled':''}>刷新</button></div>${error?`<p role="alert">${esc(error)}</p>`:''}<section class="ws-panel"><h2>付款渠道配置</h2><p>方式一：添加店铺微信后转账。方式二：直接通过收款码付款。联系方式仅向订单买家展示。</p><div class="ws-actions">${[['wechat_transfer','加微信转账'],['wechat','微信收款码'],['alipay','支付宝收款码'],['other','其他收款码']].map(([id,label])=>`<button class="ws-action" data-channel="${id}">${label} · ${channels.find(c=>c.id===id)?.enabled?'已启用':'未启用'}</button>`).join('')}</div></section><section class="ws-panel"><h2>付款记录</h2><p>待审核 ${receipts.filter(r=>r.status==='pending').length} 条。按待审核优先显示全部记录；已核实订单继续在“意向与销售”处理交付。</p>${receipts.length?`<div class="ws-table-wrap"><table class="ws-table"><thead><tr><th>订单</th><th>付款信息</th><th>OCR / 状态</th><th>操作</th></tr></thead><tbody>${[...receipts].sort((a,b)=>(b.status==='pending')-(a.status==='pending')).map(r=>{const order=window.SuohaWorkspace.snapshot().inquiries?.find(i=>i.id===r.inquiry_id);return `<tr><td>${esc(order?.reference||r.inquiry_id)}<small>${new Date(r.created_at).toLocaleString('zh-CN')}</small></td><td>¥${esc(r.submitted_fields.amount)} · ${esc(r.channel_snapshot.label)}<small>${esc(r.submitted_fields.transaction||'未填写单号')}</small></td><td>${r.ocr_confidence==null?'未识别':Math.round(r.ocr_confidence)+'%'} · ${({pending:'待人工确认',confirmed:'已确认到账',rejected:'已退回'})[r.status]}</td><td><button class="ws-action" data-review="${r.id}">查看 / 审核</button></td></tr>`;}).join('')}</tbody></table></div>`:'<p>暂无付款截图。</p>'}</section>`;if(!loaded&&!busy&&!error)load();}
 async function configure(id){const c=channels.find(c=>c.id===id)||{id,label:({wechat_transfer:'加微信转账',wechat:'微信',alipay:'支付宝',other:'其他收款'})[id],payee:'',instructions:'',enabled:false};shell(id==='wechat_transfer'?'配置微信转账':'配置收款码',`<form class="auction-form"><label>显示名称<input name="label" maxlength="60" required value="${esc(c.label)}"></label><label>收款人 / 商户名称<input name="payee" maxlength="100" required value="${esc(c.payee)}"></label><label>付款说明<textarea name="instructions" maxlength="1000">${esc(c.instructions)}</textarea></label>${c.qr_path?'<img data-qr class="payment-qr" alt="当前收款码">':''}${id==='wechat_transfer'?`<label>店铺微信号<input name="wechat_id" maxlength="100" required value="${esc(c.wechat_id||'')}"></label>`:`<label>上传收款码（JPG / PNG / WebP）<input name="image" type="file" accept="image/jpeg,image/png,image/webp" ${c.qr_path?'':'required'}></label>`}<label class="auction-consent"><input name="enabled" type="checkbox" ${c.enabled?'checked':''}>启用此收款方式</label><p role="status"></p><button type="submit" class="ws-action primary">保存收款设置</button></form>`);const f=dialog.querySelector('form');if(c.qr_path)signed(c.qr_path).then(url=>{if(f.isConnected)f.querySelector('[data-qr]').src=url;}).catch(e=>f.querySelector('[role=status]').textContent=e.message);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;try{const session=await sb.auth.getSession();const image=f.elements.image?.files[0]?await window.SuohaPaymentOCR.prepare(f.elements.image.files[0]):null;const r=await fetch('/.netlify/functions/manual-payment',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+session.data.session.access_token},body:JSON.stringify({action:'save_channel',id,label:f.elements.label.value,payee:f.elements.payee.value,instructions:f.elements.instructions.value,enabled:f.elements.enabled.checked,path:c.qr_path,wechat_id:f.elements.wechat_id?.value||null,image})});const result=await r.json();if(!r.ok)throw Error(result.error);dialog.close();await load();}catch(err){f.querySelector('[role=status]').textContent=err.message;}finally{b.disabled=false;}};}
 async function review(id){const r=receipts.find(r=>r.id===id);shell('付款截图审核','<p>正在读取…</p>');try{const [url,orderResult]=await Promise.all([signed(r.screenshot_path),sb.from('purchase_inquiries').select('reference,agreed_price,currency,status,customer_name').eq('id',r.inquiry_id).single()]);if(orderResult.error)throw orderResult.error;const o=orderResult.data,amountMismatch=Number(r.submitted_fields.amount)!==Number(o.agreed_price);shell('付款截图审核',`<p>${esc(o.reference)} · ${esc(o.customer_name)}<br>订单应付 ¥${esc(o.agreed_price)} · ${esc(o.status)}</p><a href="${esc(url)}" target="_blank" rel="noopener">打开完整截图</a><img class="payment-preview" src="${esc(url)}" alt="买家付款截图"><p>收款配置：${esc(r.channel_snapshot.label)} / ${esc(r.channel_snapshot.payee)}${r.channel_snapshot.wechat_id?' · 微信号：'+esc(r.channel_snapshot.wechat_id):''}</p><h3>买家核对后提交的信息</h3><pre>${esc(JSON.stringify(r.submitted_fields,null,2))}</pre>${amountMismatch?'<p role="alert">截图申报金额与订单金额不一致，必须核实实际到账。</p>':''}<details><summary>OCR 原文与原始提取信息（可被买家端修改，仅辅助核对）</summary><pre>${esc(r.ocr_text)}</pre><pre>${esc(JSON.stringify(r.ocr_fields,null,2))}</pre></details><p>状态：${esc(r.status)} · ${esc(r.review_note)}${r.reviewed_at?'<br>审核时间：'+esc(new Date(r.reviewed_at).toLocaleString('zh-CN')):''}</p>${r.status==='pending'?'<form class="auction-form"><label>实际确认到账金额（元）<input name="amount" type="number" min="0.01" step="0.01"></label><label>审核备注 / 退回原因<textarea name="note" maxlength="1500"></textarea></label><label class="auction-consent"><input name="verified" type="checkbox">我已在真实收款账户核对收款人、交易单号及足额到账</label><p role="status"></p><button type="submit" name="decision" value="confirmed">确认实际到账</button><button type="submit" name="decision" value="rejected" formnovalidate>退回，要求补充</button></form>':''}`);const f=dialog.querySelector('form');if(f)f.onsubmit=async e=>{e.preventDefault();const decision=e.submitter.value;f.querySelectorAll('button').forEach(b=>b.disabled=true);try{await call('review_payment_receipt',{p_id:id,p_decision:decision,p_note:f.elements.note.value,p_amount:f.elements.amount.value?Number(f.elements.amount.value):null,p_verified:f.elements.verified.checked});dialog.close();await load();window.dispatchEvent(new Event('suoha:payment-reviewed'));}catch(err){f.querySelector('[role=status]').textContent=err.message;}finally{f.querySelectorAll('button').forEach(b=>b.disabled=false);}};}catch(err){shell('读取失败',`<p role="alert">${esc(err.message)}</p>`);}}
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-refresh'))load();if(b.dataset.channel)configure(b.dataset.channel);if(b.dataset.review)review(b.dataset.review);});
 window.addEventListener('suoha:payment-reviewed',()=>window.SuohaWorkspace.load(true));
 window.SuohaPaymentAdmin={render};window.addEventListener('suoha:logout',()=>{generation++;loaded=false;busy=false;channels=[];receipts=[];error='';host.innerHTML='';dialog.close();});
 if(location.hash==='#payments')setPage('payments',false);
})();
