(() => {
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const statuses={reserved:'待付款 / 核实',paid:'已确认收款',delivered:'已交付',completed:'已完成',cancelled:'已取消'};
 const receiptStatus={pending:'等待店铺确认到账',confirmed:'人工已确认到账',rejected:'已退回，请补充付款信息'};
 const dialog=document.createElement('dialog');dialog.className='auction-dialog payment-dialog';document.body.append(dialog);
 let busy=false,opened=new Set();
 dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 const api=async(body,id)=>{const r=await fetch('/.netlify/functions/manual-payment'+(id?'?order='+encodeURIComponent(id):''),{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||'付款信息读取失败'),{status:r.status});return data;};
 function shell(title,html){dialog.innerHTML=`<button type="button" data-close>关闭 ×</button><h2>${title}</h2>${html}`;dialog.querySelector('[data-close]').onclick=()=>{if(!busy)dialog.close();};if(!dialog.open)dialog.showModal();}
 async function open(id){
  if(busy)return;shell('选择付款方式','<p role="status">正在读取订单和收款码…</p>');
  try{
   const result=await api(null,id),order=result.orders[0],active=order.receipts.find(r=>r.status!=='rejected');
   const canSubmit=order.status==='reserved'&&!active;
   shell('订单付款',`<p>${esc(order.title)}<br>订单 ${esc(order.reference)} · ${esc(statuses[order.status]||order.status)}</p><h3>应付 ¥${Number(order.amount).toFixed(2)}</h3><p>请核对收款人和金额，付款备注填写订单编号。仅在店铺核实实际到账后确认收款。</p>${order.reserved_until&&Date.now()>new Date(order.reserved_until)&&canSubmit?'<p role="alert">已超过付款期限。尚未付款请先联系店铺；已经付款仍可提交付款信息。</p>':''}${order.receipts.map(r=>`<p>${receiptStatus[r.status]}${r.note?'：'+esc(r.note):''}</p>`).join('')}${canSubmit?`<form class="auction-form"><ol class="checkout-steps" aria-label="购买进度"><li>1 订单已确认</li><li aria-current="step">2 付款并提交</li><li>3 店铺确认</li></ol><h3>选择付款方式</h3><label>付款渠道<select name="channel" required>${result.channels.map(c=>`<option value="${c.id}">${c.id==='wechat_transfer'?'加微信转账':'扫码支付 · '+esc(c.label)}</option>`).join('')}</select></label><div data-qr></div><h3>填写付款信息</h3><p>完成付款后填写支付单号，或上传账单截图自动填写。截图可不传。</p><label>支付单号（订单号 / 交易单号 / 转账单号）<input name="transaction" maxlength="100" required placeholder="可直接输入，无需等待识别"></label><label>付款时间（选填）<input name="time" maxlength="200" placeholder="例如 2026-10-08 14:30:00"></label><label>收款人（选填）<input name="payee" maxlength="200"></label><label>上传支付详情截图，自动填写（选填）<input name="screenshot" type="file" accept="image/jpeg,image/png,image/webp"></label><details class="payment-examples"><summary>查看微信 / 支付宝支付详情截图示例</summary><a href="/assets/payment-record-examples.png" target="_blank" rel="noopener"><img src="/assets/payment-record-examples.png" alt="微信转账单号与支付宝订单号的位置示例，个人及交易信息已打码" loading="lazy"></a><p>示例已打码，点击可放大。实际上传请保留订单号/转账单号、金额、付款时间和收款人信息；支付宝请填写“订单号”，不要填写“商家订单号”。</p></details><p data-screenshot-warning role="alert" hidden></p><button type="button" data-remove-image hidden>移除截图</button><img data-preview class="payment-preview" alt="待提交的付款截图" hidden><p data-ocr role="status"></p><label class="auction-consent"><input type="checkbox" name="consent" required>我已实际付款，以上信息用于店铺核对收款。</label><p data-message role="status"></p><button type="submit" class="button button-dark">提交付款信息</button></form>`:'<div class="checkout-state"><p>店铺核实后会更新订单状态，请勿重复付款。</p><button type="button" data-reload>刷新订单状态</button></div>'}`);
   if(!canSubmit){dialog.querySelector('[data-reload]').onclick=()=>open(id);return;}
   const f=dialog.querySelector('form'),button=f.querySelector('[type=submit]'),message=f.querySelector('[data-message]');let prepared='',request=crypto.randomUUID();
   function qr(){const c=result.channels.find(c=>c.id===f.elements.channel.value);f.querySelector('[data-qr]').innerHTML=c?`<p>收款人：<strong>${esc(c.payee)}</strong></p>${c.id==='wechat_transfer'?`<p>店铺微信号：<strong>${esc(c.wechat_id)}</strong></p><p>打开微信 → 添加朋友 → 搜索以上微信号，添加店铺后进行微信转账。请备注订单编号。</p>`:`<img class="payment-qr" src="${esc(c.url)}" alt="${esc(c.label)}收款码"><p>请使用对应付款应用扫描，或保存收款码后在付款应用中识别。</p>`}<p>${esc(c.instructions)}</p>`:'<p>店铺暂未启用付款渠道，请联系店铺。</p>';}
   qr();f.elements.channel.onchange=qr;
   let imageVersion=0,preparing=false;const dirtyFields=new Set(),autoValues={};
   for(const k of ['transaction','time','payee'])f.elements[k].addEventListener('input',()=>{dirtyFields.add(k);request=crypto.randomUUID();});
   function clearImage(){imageVersion++;prepared='';preparing=false;request=crypto.randomUUID();f.elements.screenshot.value='';const preview=f.querySelector('[data-preview]');preview.hidden=true;preview.removeAttribute('src');f.querySelector('[data-ocr]').textContent='';f.querySelector('[data-screenshot-warning]').hidden=true;f.querySelector('[data-remove-image]').hidden=true;button.disabled=!result.channels.length;for(const k of ['transaction','time','payee']){if(!dirtyFields.has(k)&&f.elements[k].value===autoValues[k])f.elements[k].value='';delete autoValues[k];}}
   f.querySelector('[data-remove-image]').onclick=clearImage;button.disabled=!result.channels.length;
   f.elements.channel.addEventListener('change',()=>{request=crypto.randomUUID();});
   f.elements.screenshot.onchange=async()=>{
    if(busy)return;const file=f.elements.screenshot.files[0];if(!file){clearImage();return;}
    const version=++imageVersion;prepared='';preparing=true;button.disabled=true;request=crypto.randomUUID();message.textContent='';
    const m=f.querySelector('[data-ocr]'),warning=f.querySelector('[data-screenshot-warning]');warning.hidden=true;
    f.querySelector('[data-preview]').hidden=true;f.querySelector('[data-remove-image]').hidden=false;
    for(const k of ['transaction','time','payee'])if(!dirtyFields.has(k)&&f.elements[k].value===autoValues[k]){f.elements[k].value='';delete autoValues[k];}
    const current=()=>version===imageVersion&&f.isConnected&&!busy;
    try{
     const image=await window.SuohaPaymentOCR.prepare(file);if(!current())return;prepared=image;preparing=false;button.disabled=!result.channels.length;
     const preview=f.querySelector('[data-preview]');preview.src=image;preview.hidden=false;m.textContent='正在自动填写，也可手动输入单号后直接提交。';
     try{
      const result=await window.SuohaPaymentOCR.recognize(image);if(!current())return;
      let filled=0;for(const k of ['transaction','time','payee'])if(!dirtyFields.has(k)&&result.fields[k]){f.elements[k].value=result.fields[k];autoValues[k]=result.fields[k];filled++;}
      m.textContent=filled?'已自动填写，请核对后提交。':'未能自动填写，请手动输入支付单号。';
      if(!result.fields.transaction&&!f.elements.transaction.value.trim()){warning.textContent='未识别到订单号/转账单号。请点击账单中本次支付记录并截图，上传包含订单号/转账单号的支付记录截图。也可直接手动填写。';warning.hidden=false;}
     }catch{if(current())m.textContent='自动填写暂不可用，请手动输入支付单号，仍可正常提交。';}
    }catch(err){if(current()){prepared='';m.textContent=err.message;}}
    finally{if(current()){preparing=false;button.disabled=!result.channels.length;}}
   };
   f.onsubmit=async e=>{e.preventDefault();if(busy||preparing)return;if(!f.elements.transaction.value.trim()){message.textContent='请填写支付单号，或上传包含订单号/转账单号的账单截图。';f.elements.transaction.focus();return;}busy=true;imageVersion++;button.disabled=true;message.textContent='正在提交付款信息…';const controls=[...f.querySelectorAll('input,select,button')];controls.forEach(c=>c.disabled=true);try{await api({action:'receipt',order_id:id,request_id:request,channel:f.elements.channel.value,image:prepared||null,fields:Object.fromEntries(['transaction','time','payee'].map(k=>[k,f.elements[k].value]))});busy=false;await open(id);}catch(err){message.textContent=err.message;}finally{busy=false;controls.forEach(c=>c.disabled=false);button.disabled=!result.channels.length;}};
  }catch(err){shell('付款暂不可用',`<p role="alert">${esc(err.message)}</p>`);}
 }
 function mount(host,order,auto=false){if(!order?.id||host.querySelector('[data-payment-order]'))return;const b=document.createElement('button');b.type='button';b.dataset.paymentOrder=order.id;b.className='button button-dark';b.textContent=order.status==='reserved'?'付款 / 查看进度':'查看订单进度';b.onclick=()=>open(order.id);host.append(b);if(auto&&order.status==='reserved'&&!opened.has(order.id)&&!dialog.open){opened.add(order.id);open(order.id);}}
 function purchase(item){if(item.sale_status!=='available'||item.currency!=='CNY'||!(Number(item.asking_price)>0)||['open','won'].includes(item.auction?.status))return;const host=document.querySelector('#detailView .detail-purchase');if(!host)return;const b=document.createElement('button');b.type='button';b.className='button button-dark';b.textContent='登录后购买 · ¥'+Number(item.asking_price).toFixed(2);host.prepend(b);const hint=host.querySelector('p')||document.createElement('p');hint.className='purchase-login-hint';hint.textContent='登录后可购买、提交付款信息并查看订单；咨询无需登录。';if(!hint.isConnected)host.append(hint);host.querySelector('#openInquiry')?.classList.add('purchase-secondary');api().then(()=>{if(host.isConnected){b.textContent='立即购买 · ¥'+Number(item.asking_price).toFixed(2);hint.textContent='已登录，可购买并在“我的订单”查看付款与交付进度。';}}).catch(()=>{});const request=crypto.randomUUID();b.onclick=async()=>{b.disabled=true;try{await api();shell('确认购买',`<p>${esc(item.title)} · ¥${Number(item.asking_price).toFixed(2)}</p><p>确认后为你预留 2 小时并展示收款码。运费及交付条件以个体说明和店铺沟通为准。</p><button data-confirm>确认订单并付款</button><p role="status"></p>`);dialog.querySelector('[data-confirm]').onclick=async e=>{e.target.disabled=true;try{const r=await api({action:'purchase',listing_id:item.id,request_id:request});await open(r.id);}catch(err){dialog.querySelector('[role=status]').textContent=err.message;e.target.disabled=false;}};}catch(err){if(/登录/.test(err.message))window.SuohaAuctionPublic.login(()=>{if(host.isConnected){b.textContent='立即购买 · ¥'+Number(item.asking_price).toFixed(2);b.click();}});else shell('暂不能购买',`<p role="alert">${esc(err.message)}</p>`);}finally{b.disabled=false;}};}
 async function orders(host){const box=document.createElement('section');host.append(box);try{const r=await api();box.innerHTML='<h3>我的订单</h3>'+r.orders.map(o=>`<article><p>${esc(o.title)} · ${esc(o.reference)}<br>¥${esc(o.amount)} · ${esc(statuses[o.status]||o.status)}</p></article>`).join('');box.querySelectorAll('article').forEach((el,i)=>mount(el,r.orders[i]));}catch(err){box.textContent=err.message;}}
 window.SuohaPayments={mount,open,purchase,orders};
})();
