(() => {
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const statuses={reserved:'待付款 / 核实',paid:'已确认收款',delivered:'已交付',completed:'已完成',cancelled:'已取消'};
 const receiptStatus={pending:'等待人工确认到账',confirmed:'人工已确认到账',rejected:'已退回，请补充截图'};
 const dialog=document.createElement('dialog');dialog.className='auction-dialog payment-dialog';document.body.append(dialog);
 let busy=false,opened=new Set();
 dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 const api=async(body,id)=>{const r=await fetch('/.netlify/functions/manual-payment'+(id?'?order='+encodeURIComponent(id):''),{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'付款信息读取失败');return data;};
 function shell(title,html){dialog.innerHTML=`<button type="button" data-close>关闭 ×</button><h2>${title}</h2>${html}`;dialog.querySelector('[data-close]').onclick=()=>{if(!busy)dialog.close();};if(!dialog.open)dialog.showModal();}
 async function open(id){
  if(busy)return;shell('选择付款方式','<p role="status">正在读取订单和收款码…</p>');
  try{
   const result=await api(null,id),order=result.orders[0],active=order.receipts.find(r=>r.status!=='rejected');
   const canSubmit=order.status==='reserved'&&!active;
   shell('订单付款',`<p>${esc(order.title)}<br>订单 ${esc(order.reference)} · ${esc(statuses[order.status]||order.status)}</p><h3>应付 ¥${Number(order.amount).toFixed(2)}</h3><p>请核对收款人和金额，付款备注填写订单编号。仅在店铺核实实际到账后确认收款。</p>${order.reserved_until&&Date.now()>new Date(order.reserved_until)&&canSubmit?'<p role="alert">已超过付款期限。尚未付款请先联系店铺；已经付款仍可上传截图。</p>':''}${order.receipts.map(r=>`<p>${receiptStatus[r.status]}${r.note?'：'+esc(r.note):''}</p>`).join('')}${canSubmit?`<form class="auction-form"><p><strong>方式一：添加店铺微信后，使用微信转账。</strong><br><strong>方式二：直接通过二维码支付。</strong><br>请选择店铺已启用的一种方式付款，请勿重复支付。</p><label>付款渠道<select name="channel" required>${result.channels.map(c=>`<option value="${c.id}">${c.id==='wechat_transfer'?'方式一：加微信转账':'方式二：扫码支付 · '+esc(c.label)}</option>`).join('')}</select></label><div data-qr></div><p><strong>请点击账单中本次支付记录并截图，上传包含订单号/转账单号的支付记录截图。请保留金额、付款时间及页面上的收款人信息。</strong>请勿只上传付款成功提示页。</p><label>支付详情截图（须包含支付单号）<input name="screenshot" type="file" accept="image/jpeg,image/png,image/webp" required></label><details class="payment-examples"><summary>查看微信 / 支付宝支付详情截图示例</summary><a href="/assets/payment-record-examples.png" target="_blank" rel="noopener"><img src="/assets/payment-record-examples.png" alt="微信转账单号与支付宝订单号的位置示例，个人及交易信息已打码" loading="lazy"></a><p>示例已打码，点击可放大。实际上传请保留订单号/转账单号、金额、付款时间和收款人信息；支付宝请填写“订单号”，不要填写“商家订单号”。</p></details><p data-screenshot-warning role="alert" hidden></p><p>截图会保存在店铺私有记录中。中文 OCR 在本机识别，请核对识别结果；识别失败也可填写信息提交人工审核。</p><img data-preview class="payment-preview" alt="待提交的付款截图" hidden><p data-ocr role="status"></p><label>截图付款金额（元）<input name="amount" type="number" min="0.01" max="9999999999.99" step="0.01" required></label><label>支付单号（订单号 / 交易单号 / 转账单号）<input name="transaction" maxlength="100" required></label><label>付款时间<input name="time" maxlength="200" placeholder="例如 2026-10-08 14:30:00"></label><label>截图收款人<input name="payee" maxlength="200"></label><details><summary>查看 OCR 原文</summary><pre data-raw></pre></details><label class="auction-consent"><input type="checkbox" name="consent" required>我已实际付款，并同意店铺保存截图用于交易核对。</label><p data-message role="status"></p><button type="submit" disabled>提交付款截图，等待人工确认</button></form>`:'<p>如有疑问请联系店铺；待核实期间请勿重复付款。</p>'}`);
   if(!canSubmit)return;
   const f=dialog.querySelector('form'),button=f.querySelector('[type=submit]'),message=f.querySelector('[data-message]');let prepared='',ocr={text:'',confidence:null,fields:{}},request=crypto.randomUUID();
   function qr(){const c=result.channels.find(c=>c.id===f.elements.channel.value);f.querySelector('[data-qr]').innerHTML=c?`<p>收款人：<strong>${esc(c.payee)}</strong></p>${c.id==='wechat_transfer'?`<p>店铺微信号：<strong>${esc(c.wechat_id)}</strong></p><p>打开微信 → 添加朋友 → 搜索以上微信号，添加店铺后进行微信转账。请备注订单编号。</p>`:`<img class="payment-qr" src="${esc(c.url)}" alt="${esc(c.label)}收款码"><p>请使用对应付款应用扫描，或保存收款码后在付款应用中识别。</p>`}<p>${esc(c.instructions)}</p>`:'<p>店铺暂未启用付款渠道，请联系店铺。</p>';}
   qr();f.elements.channel.onchange=qr;
   f.elements.screenshot.onchange=async()=>{if(busy)return;button.disabled=true;busy=true;f.elements.screenshot.disabled=true;message.textContent="";const warning=f.querySelector("[data-screenshot-warning]");warning.hidden=true;warning.textContent="";const oldPreview=f.querySelector("[data-preview]");oldPreview.hidden=true;oldPreview.removeAttribute("src");prepared='';ocr={text:'',confidence:null,fields:{}};request=crypto.randomUUID();const m=f.querySelector('[data-ocr]');f.querySelector('[data-raw]').textContent='';for(const k of ['amount','transaction','time','payee'])f.elements[k].value='';try{prepared=await window.SuohaPaymentOCR.prepare(f.elements.screenshot.files[0]);const preview=f.querySelector('[data-preview]');preview.src=prepared;preview.hidden=false;m.textContent='正在识别…';try{ocr=await window.SuohaPaymentOCR.recognize(prepared,text=>m.textContent=text);for(const k of ['amount','transaction','time','payee'])f.elements[k].value=ocr.fields[k]||'';f.querySelector('[data-raw]').textContent=ocr.text;if(!ocr.fields.transaction){warning.textContent='未识别到订单号/转账单号，可能上传了错误页面。请点击账单中本次支付记录并截图，上传包含订单号/转账单号的支付记录截图。如果截图中已有清晰单号，可手动填写后提交人工核对。';warning.hidden=false;}m.textContent=`识别完成（置信度 ${Math.round(ocr.confidence)}%），请核对后提交。`;}catch(err){m.textContent='OCR 未完成：'+err.message+'。可手动填写后提交。';warning.textContent='请点击账单中本次支付记录并截图，上传包含订单号/转账单号的支付记录截图。';warning.hidden=false;}}catch(err){m.textContent=err.message;}finally{busy=false;f.elements.screenshot.disabled=false;button.disabled=!prepared||!result.channels.length;}};
   f.onsubmit=async e=>{e.preventDefault();if(busy||!prepared)return;if(!f.elements.transaction.value.trim()){message.textContent='请点击账单中本次支付记录并截图，上传包含订单号/转账单号的支付记录截图。';f.elements.transaction.focus();return;}busy=true;button.disabled=true;message.textContent='正在保存…';try{await api({action:'receipt',order_id:id,request_id:request,channel:f.elements.channel.value,image:prepared,ocr_text:ocr.text,ocr_fields:ocr.fields,confidence:ocr.confidence,fields:Object.fromEntries(['amount','transaction','time','payee'].map(k=>[k,f.elements[k].value]))});busy=false;await open(id);}catch(err){message.textContent=err.message;}finally{busy=false;button.disabled=false;}};
  }catch(err){shell('付款暂不可用',`<p role="alert">${esc(err.message)}</p>`);}
 }
 function mount(host,order,auto=false){if(!order?.id||host.querySelector('[data-payment-order]'))return;const b=document.createElement('button');b.type='button';b.dataset.paymentOrder=order.id;b.className='button button-dark';b.textContent=order.status==='reserved'?'付款方式 / 上传截图':'查看付款记录';b.onclick=()=>open(order.id);host.append(b);if(auto&&order.status==='reserved'&&!opened.has(order.id)&&!dialog.open){opened.add(order.id);open(order.id);}}
 function purchase(item){if(item.sale_status!=='available'||item.currency!=='CNY'||!(Number(item.asking_price)>0)||['open','won'].includes(item.auction?.status))return;const host=document.querySelector('#detailView .detail-purchase');if(!host)return;const b=document.createElement('button');b.type='button';b.className='button button-dark';b.textContent='确认购买 · ¥'+Number(item.asking_price).toFixed(2);host.prepend(b);const request=crypto.randomUUID();b.onclick=async()=>{b.disabled=true;try{await api();shell('确认购买',`<p>${esc(item.title)} · ¥${Number(item.asking_price).toFixed(2)}</p><p>确认后为你预留 2 小时并展示收款码。运费及交付条件以个体说明和店铺沟通为准。</p><button data-confirm>确认订单并查看收款码</button><p role="status"></p>`);dialog.querySelector('[data-confirm]').onclick=async e=>{e.target.disabled=true;try{const r=await api({action:'purchase',listing_id:item.id,request_id:request});await open(r.id);}catch(err){dialog.querySelector('[role=status]').textContent=err.message;e.target.disabled=false;}};}catch(err){if(/登录/.test(err.message))window.SuohaAuctionPublic.login();else shell('暂不能购买',`<p role="alert">${esc(err.message)}</p>`);}finally{b.disabled=false;}};}
 async function orders(host){const box=document.createElement('section');host.append(box);try{const r=await api();box.innerHTML='<h3>我的购买与付款记录</h3>'+r.orders.map(o=>`<article><p>${esc(o.title)} · ${esc(o.reference)}<br>¥${esc(o.amount)} · ${esc(statuses[o.status]||o.status)}</p></article>`).join('');box.querySelectorAll('article').forEach((el,i)=>mount(el,r.orders[i]));}catch(err){box.textContent=err.message;}}
 window.SuohaPayments={mount,open,purchase,orders};
})();
