const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
const {handler}=require('../netlify/functions/auction-api');
test('auction transaction lifecycle: privacy, retries, deadline, winner and sales exclusion',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);create table profiles(id uuid primary key,role text,active boolean);
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function can_edit_app() returns boolean language sql security definer as $$select exists(select 1 from profiles where id=auth.uid() and active and role='admin')$$;
 create table snakes(id text primary key,series text,sex text,birth_date date,gene_text text,status text);
 create table genes(id text primary key,name_zh text);create table snake_genes(snake_id text,gene_id text,state text,probability numeric);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key,bucket_id text,name text);alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to anon,authenticated,service_role;
 insert into auth.users values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');insert into profiles values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','admin',true);
 insert into snakes values('S1','test','F','2025-01-01','test','active');`);
 for(const f of ['019_public_catalog_and_sales.sql','024_listing_removal.sql','029_auctions.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));
 const listing='11111111-1111-4111-8111-111111111111';
 await db.query("insert into specimen_listings(id,snake_id,slug,title,published,sale_status) values($1,'S1','s1','Test',true,'available')",[listing]);
 await db.exec("set request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';set role authenticated");
 const create=()=>db.query("select create_auction($1,1000,50,30,clock_timestamp()-interval '1 minute',24,72,2) id",[listing]);
 const id=(await create()).rows[0].id;
 await assert.rejects(create(),/duplicate key/);
 await assert.rejects(db.query("update specimen_listings set published=false where id=$1",[listing]),/拍卖进行中/);
 await assert.rejects(db.query("select delete_specimen_listing($1)",[listing]),/拍卖进行中/);
 await assert.rejects(db.query("select read_auctions($1,'')",[listing]),/permission denied/);
 await assert.rejects(db.query('select * from auction_buyers'),/permission denied/);
 await db.exec('reset role');
 await assert.rejects(db.query("select submit_purchase_inquiry(gen_random_uuid(),$1,'customer','wx-test','','hash')",[listing]),/正在拍卖/);
 await db.query("select auction_identity('register','buyer1','salt:hash','private-contact-1','token1')");
 await db.query("select auction_identity('register','buyer2','salt:hash','private-contact-2','token2')");
 const bid=(token,amount,key='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')=>db.query('select place_auction_bid($1,$2,$3,$4)',[token,id,amount,key]);
 await assert.rejects(bid('',1000),/请先登录/);
 await assert.rejects(bid('token1',999),/报价低于/);
 await bid('token1',1000);await bid('token1',1000);
 assert.equal((await db.query('select bid_count from auctions where id=$1',[id])).rows[0].bid_count,1);
 await assert.rejects(bid('token2',1000),/请求编号冲突/);
 await assert.rejects(bid('token1',1050,'cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/你已领先/);
 await assert.rejects(bid('token2',1049,'cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/报价低于/);
 await bid('token2',1050,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');
 const state=(await db.query('select read_auctions($1,$2) data',[listing,'token1'])).rows[0].data;
 assert.equal(state.items[0].leading,false);assert.equal(state.items[0].participated,true);assert.equal(state.items[0].bid_count,2);
 assert.equal(state.items[0].bids[1].mine,true);assert.equal(JSON.stringify(state).includes('private-contact'),false);
 assert.equal(JSON.stringify(state).includes('password_hash'),false);
 await db.query("update auctions set starts_at=clock_timestamp()-interval '2 hours',ends_at=clock_timestamp()-interval '1 second' where id=$1",[id]);
 await assert.rejects(bid('token1',1100,'dddddddd-dddd-4ddd-8ddd-dddddddddddd'),/已结束/);
 await db.query('select settle_auction($1)',[id]);await db.query('select settle_auction($1)',[id]);
 assert.equal((await db.query('select count(*) n from purchase_inquiries')).rows[0].n,1);
 const winner=(await db.query('select read_auctions(null,$1) data',['token2'])).rows[0].data.items[0];
 assert.equal(winner.status,'won');assert.equal(winner.order.status,'reserved');assert.equal(winner.order.amount,1050);
 assert.equal((await db.query('select read_auctions(null,$1) data',['token1'])).rows[0].data.items[0].order,null);
 await db.exec('set role anon');await assert.rejects(db.query('select * from auctions'),/permission denied/);
 const summary=(await db.query('select auction_catalog(array[$1]::uuid[]) data',[listing])).rows[0].data;
 assert.equal(summary[listing].status,'won');assert.equal(summary[listing].winner_id,undefined);
 await db.exec('reset role;set role authenticated');
 const inquiry=(await db.query('select id from purchase_inquiries')).rows[0].id;
 await db.query("select manage_specimen_sale($1,'paid')",[inquiry]);await db.query("select manage_specimen_sale($1,'deliver')",[inquiry]);await db.query("select manage_specimen_sale($1,'complete')",[inquiry]);
 assert.equal((await db.query('select sale_status from specimen_listings')).rows[0].sale_status,'sold');
 await db.exec('reset role');
 // No-bid expiry, cancellation and the hard deadline use the same state machine.
 await db.exec("insert into snakes values('S2','test','M','2025-01-01','test','active');insert into specimen_listings(id,snake_id,slug,title,published,sale_status) values('22222222-2222-4222-8222-222222222222','S2','s2','Second',true,'available');set role authenticated");
 const secondListing='22222222-2222-4222-8222-222222222222';
 const second=()=>db.query("select create_auction($1,1000,50,30,clock_timestamp()-interval '1 minute',1,2,2) id",[secondListing]);
 const cancelled=(await second()).rows[0].id;
 await assert.rejects(db.query("select cancel_auction($1,'')",[cancelled]),/填写取消原因/);
 await db.query("select cancel_auction($1,'健康复查，暂缓出售')",[cancelled]);
 const unsold=(await second()).rows[0].id;
 await db.exec('reset role');
 await db.query("update auctions set starts_at=clock_timestamp()-interval '2 hours',ends_at=clock_timestamp()-interval '1 second' where id=$1",[unsold]);
 await db.query('select settle_due_auctions()');
 assert.equal((await db.query('select status from auctions where id=$1',[unsold])).rows[0].status,'unsold');
 await db.exec('set role authenticated');const capped=(await second()).rows[0].id;await db.exec('reset role');
 await db.query("update auctions set ends_at=clock_timestamp()+interval '1 minute',hard_ends_at=clock_timestamp()+interval '2 minutes' where id=$1",[capped]);
 await db.query("select place_auction_bid('token1',$1,1000,gen_random_uuid())",[capped]);
 assert.equal((await db.query('select ends_at=hard_ends_at capped from auctions where id=$1',[capped])).rows[0].capped,true);
 const simultaneous=await Promise.allSettled(['eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','ffffffff-ffff-4fff-8fff-ffffffffffff'].map(key=>db.query("select place_auction_bid('token2',$1,1050,$2)",[capped,key])));
 assert.equal(simultaneous.filter(r=>r.status==='fulfilled').length,1);
 assert.equal((await db.query('select bid_count from auctions where id=$1',[capped])).rows[0].bid_count,2);
 for(let i=0;i<30;i++)assert.equal((await db.query("select auction_rate('ip:test') ok")).rows[0].ok,true);
 assert.equal((await db.query("select auction_rate('ip:test') ok")).rows[0].ok,false);
 await db.query("select auction_identity('logout','','','','token1')");
 assert.equal((await db.query("select read_auctions(null,'token1') data")).rows[0].data.username,null);
 }finally{await db.close();}
});

test('auction API rejects invalid inputs, cross-site requests and unauthenticated bids',async()=>{
 process.env.SUPABASE_SERVICE_ROLE_KEY='secret';process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='public';process.env.INQUIRY_HASH_SECRET='hash';
 const original=global.fetch;const calls=[];
 global.fetch=async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return {ok:true,json:async()=>true};};
 const event={httpMethod:'POST',headers:{'content-type':'application/json','x-nf-client-connection-ip':'127.0.0.1'},body:'{}'};
 try{
 assert.equal((await handler({...event,headers:{'content-type':'text/plain'}})).statusCode,403);
 assert.equal((await handler({...event,headers:{...event.headers,'sec-fetch-site':'cross-site'}})).statusCode,403);
 assert.equal((await handler({...event,body:'null'})).statusCode,400);
 assert.equal((await handler({...event,body:JSON.stringify({action:'bid'})})).statusCode,401);
 assert.equal((await handler({...event,body:JSON.stringify({action:'register',username:'abc',password:'short'})})).statusCode,400);
 assert.equal((await handler({httpMethod:'GET',queryStringParameters:{listing_id:'invalid'}})).statusCode,400);
 assert.equal(calls.some(c=>c.url.endsWith('/place_auction_bid')),false);
 assert.equal(calls.some(c=>JSON.stringify(c.body).includes('127.0.0.1')),false);
 }finally{global.fetch=original;}
});
