const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
test('migrations enforce public boundary, transaction states and actual offspring lineage',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);create table public.profiles(id uuid primary key,role text,active boolean,email text,display_name text);
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function public.can_edit_app() returns boolean language sql security definer as $$select exists(select 1 from public.profiles where id=auth.uid() and active and role in ('editor','admin'))$$;
 create table snakes(id text primary key,series text,sex text,birth_date date,mature_date date,gene_text text,status text,price numeric,investor text,origin text,sire_id text,dam_id text,clutch_id bigint,strategic_score integer);
 create table genes(id text primary key,name_zh text);create table snake_genes(snake_id text,gene_id text,state text,probability numeric);
 create table annual_breeding_plans(id bigint primary key,female_snake_id text,male_snake_id text,review_status text);
 create table breeding_events(id bigint generated always as identity primary key,plan_id bigint,female_snake_id text,male_snake_id text,paired_at date,status text,notes text);
 create table clutches(id bigint generated always as identity primary key,clutch_code text,breeding_event_id bigint,female_snake_id text,male_snake_id text,laid_date date,egg_count integer,fertile_egg_count integer,hatched_count integer,status text);
 create table investment_expenses(id uuid primary key default gen_random_uuid(),category text,amount numeric,owner_id uuid);
 create table route_nodes(id text primary key,x numeric,y numeric);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to anon,authenticated,service_role;
 grant select,update on public.snakes to authenticated;
 insert into auth.users values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');insert into profiles values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','admin',true,'1442399241@qq.com','suohama');
 insert into snakes(id,series,sex,gene_text,status,price) values('M01','系列','F','母本','active',12345),('M02','系列','M','公本','active',54321);
 `);
 for(const name of ['019_public_catalog_and_sales.sql','020_breeding_operations.sql','021_acquisition_cost_history.sql','022_route_move_transactions.sql','023_inventory_libraries.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 await db.exec(`insert into specimen_listings(id,snake_id,slug,title,published,sale_status,asking_price) values('11111111-1111-4111-8111-111111111111','M01','m01','公开母本',true,'available',3500),('22222222-2222-4222-8222-222222222222','M02','m02','私有公本',false,'display',null);`);
 await db.exec('set role anon');
 const publicData=(await db.query('select public_catalog() as data')).rows[0].data;
 assert.equal(publicData.items.length,1);assert.equal(publicData.items[0].asking_price,3500);assert.equal(publicData.items[0].price,undefined);assert.equal(publicData.items[0].investor,undefined);
 await assert.rejects(db.query('select * from specimen_listings'),/permission denied/);
 await assert.rejects(db.query('select * from purchase_inquiries'),/permission denied/);
 await assert.rejects(db.query('select * from inventory_sale_states()'),/permission denied/);
 await db.exec('reset role');
 await assert.rejects(db.query("update snakes set status='retired' where id='M01'"),/Resolve availability/);
 const makeInquiry=async(n)=>db.query(`select submit_purchase_inquiry($1,'11111111-1111-4111-8111-111111111111','客户','contact','留言','fingerprint') as data`,[`${n}3333333-3333-4333-8333-333333333333`]);
 const first=(await makeInquiry(1)).rows[0].data;assert.equal((await makeInquiry(1)).rows[0].data.reference,first.reference);
 await makeInquiry(2);const inquiries=(await db.query('select id from purchase_inquiries order by created_at,id')).rows;
 await db.exec(`set request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';set role authenticated;`);
 await assert.rejects(db.query(`update specimen_listings set sale_status='sold' where slug='m01'`),/Use sales workflow/);
 const saleState=async()=> (await db.query("select sale_state from inventory_sale_states() where snake_id='M01'")).rows[0].sale_state;
 assert.equal(await saleState(),'available');
 await db.query("update specimen_listings set published=false where slug='m01'");assert.equal(await saleState(),'normal');
 await db.query("update specimen_listings set published=true,sale_status='display' where slug='m01'");assert.equal(await saleState(),'normal');
 await db.query("update specimen_listings set sale_status='available' where slug='m01'");assert.equal(await saleState(),'available');
 const action=(id,name,until=null,amount=null)=>db.query('select manage_specimen_sale($1,$2,$3,$4,$5)',[id,name,'测试记录',until,amount]);
 await action(inquiries[0].id,'reserve','2099-01-01',3500);
 await assert.rejects(action(inquiries[1].id,'reserve','2099-01-01',3500),/not available/);
 await assert.rejects(action(inquiries[0].id,'complete'),/Invalid transition/);
 await action(inquiries[0].id,'paid');await action(inquiries[0].id,'deliver');await action(inquiries[0].id,'complete');
 assert.equal((await db.query(`select sale_status from specimen_listings where slug='m01'`)).rows[0].sale_status,'sold');
 const event=(await db.query(`select record_breeding_event(null,null,'M01','M02','2026-01-01','paired','真实记录') as id`)).rows[0].id;
 const clutch=(await db.query(`select record_clutch(null,$1,'CL-1','2026-02-01',3,2,1,'hatched') as id`,[event])).rows[0].id;
 await db.query(`select register_hatchling($1,'M03','U','2026-03-01','系列','待确认','owner')`,[clutch]);
 await assert.rejects(db.query(`select register_hatchling($1,'M04','U','2026-03-01','系列','待确认','owner')`,[clutch]),/already registered/);
 await db.exec('reset role');const hatch=(await db.query(`select * from snakes where id='M03'`)).rows[0];assert.equal(hatch.dam_id,'M01');assert.equal(hatch.sire_id,'M02');assert.equal(hatch.origin,'produced');
 assert.equal(hatch.inventory_library,'nursery');
 await db.exec('set role authenticated');
 await assert.rejects(db.query("update snakes set inventory_library='stock' where id='M03'"),/transfer workflow/);
 await db.query("select transfer_inventory_animal('M03','stock')");
 await db.exec('reset role');
 assert.equal((await db.query("select inventory_library from snakes where id='M03'")).rows[0].inventory_library,'stock');
 assert.equal((await db.query("select count(*) from snakes where id='M03'")).rows[0].count,1);
 assert.equal((await db.query("select count(*) from inventory_transfers where individual_id='M03'")).rows[0].count,1);
 await db.exec("update profiles set role='viewer';set role authenticated");
 await assert.rejects(db.query("select transfer_inventory_animal('M03','nursery')"),/Not authorized/);
 await db.exec("reset role;update profiles set role='admin'");
 assert.equal((await db.query("select status from snakes where id='M01'")).rows[0].status,'sold');
 await assert.rejects(db.query("update snakes set status='active' where id='M01'"),/separate correction workflow/);
 const cost=(await db.query(`select * from snake_acquisition_costs where snake_id='M01'`)).rows[0];assert.equal(Number(cost.amount),12345);
 await db.query(`insert into investment_expenses(category,amount,owner_id,acquisition_id) values('population',12345,auth.uid(),$1)`,[cost.id]);
 await assert.rejects(db.query(`insert into investment_expenses(category,amount,owner_id,acquisition_id) values('population',12345,auth.uid(),$1)`,[cost.id]),/duplicate key/);
 await assert.rejects(db.query(`insert into investment_expenses(category,amount,owner_id,acquisition_id) values('equipment',1,auth.uid(),$1)`,[cost.id]),/population category/);
 await db.exec(`insert into snakes(id,price,status,sex) values('Y99',777,'active','U');delete from snakes where id='Y99';`);
 const retained=(await db.query(`select * from snake_acquisition_costs where individual_id='Y99'`)).rows[0];assert.equal(retained.snake_id,null);assert.equal(Number(retained.amount),777);
 await db.exec(`insert into route_nodes values('node-1',100,200);set role authenticated;`);
 await db.query(`select move_route_node('node-1',110,210,100,200)`);
 await assert.rejects(db.query(`select move_route_node('node-1',120,220,100,200)`),/another session/);
 await db.query(`select move_route_node('node-1',100,200,110,210)`);
 }finally{await db.close();}
});
