const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
test('migrations enforce public boundary, transaction states and actual offspring lineage',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);create table public.profiles(id uuid primary key,role text,active boolean,email text,display_name text);
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function public.can_edit_app() returns boolean language sql security definer as $$select exists(select 1 from public.profiles where id=auth.uid() and active and role in ('editor','admin'))$$;
 create table snakes(id text primary key,series text,sex text,birth_date date,mature_date date,gene_text text,status text,price numeric,investor text,origin text,sire_id text,dam_id text,clutch_id bigint,strategic_score integer);
 create table genes(id text primary key,name_zh text);create table snake_genes(snake_id text,gene_id text,state text,probability numeric);
 create table annual_breeding_plans(id bigint primary key,female_snake_id text,male_snake_id text,review_status text,project_name text,plan_year integer,status text);
 create table breeding_events(id bigint generated always as identity primary key,plan_id bigint,female_snake_id text,male_snake_id text,paired_at date,status text,notes text);
 create table clutches(id bigint generated always as identity primary key,clutch_code text,breeding_event_id bigint,female_snake_id text,male_snake_id text,laid_date date,egg_count integer,fertile_egg_count integer,hatched_count integer,status text);
 create table investment_expenses(id uuid primary key default gen_random_uuid(),category text,amount numeric,owner_id uuid);
 create table route_nodes(id text primary key,x numeric,y numeric);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to anon,authenticated,service_role;
 grant select,update on public.snakes to authenticated;
 insert into auth.users values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');insert into profiles values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','admin',true,'1442399241@qq.com','suohama');
 insert into snakes(id,series,sex,gene_text,status,price) values('M01','系列','F','母本','active',12345),('M02','系列','M','公本','active',54321);
 `);
 for(const name of ['019_public_catalog_and_sales.sql','020_breeding_operations.sql','021_acquisition_cost_history.sql','022_route_move_transactions.sql','023_inventory_libraries.sql','024_listing_removal.sql','025_breeding_calendar.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 await db.exec(`insert into specimen_listings(id,snake_id,slug,title,published,sale_status,asking_price) values('11111111-1111-4111-8111-111111111111','M01','m01','公开母本',true,'available',3500),('22222222-2222-4222-8222-222222222222','M02','m02','私有公本',false,'display',null);`);
 await db.exec('set role anon');
 const publicData=(await db.query('select public_catalog() as data')).rows[0].data;
 assert.equal(publicData.items.length,1);assert.equal(publicData.items[0].asking_price,3500);assert.equal(publicData.items[0].price,undefined);assert.equal(publicData.items[0].investor,undefined);
 await assert.rejects(db.query('select * from specimen_listings'),/permission denied/);
 await assert.rejects(db.query('select * from purchase_inquiries'),/permission denied/);
 await assert.rejects(db.query('select * from inventory_sale_states()'),/permission denied/);
 await db.exec('reset role');
 await assert.rejects(db.query("update snakes set status='retired' where id='M01'"),/Resolve availability/);
 const makeInquiry=async(n)=>db.query(`select submit_purchase_inquiry($1,'11111111-1111-4111-8111-111111111111','客户','contact','留言','fingerprint') as data`,[`${n}3333333-3333-4333-8333-333333333333`]);
 const first=(await makeInquiry(1)).rows[0].data;assert.equal((await makeInquiry(1)).rows[0].data.reference,first.reference);
 await makeInquiry(2);const inquiries=(await db.query('select id from purchase_inquiries order by created_at,id')).rows;
 await db.exec(`set request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';set role authenticated;`);
 await assert.rejects(db.query(`update specimen_listings set sale_status='sold' where slug='m01'`),/Use sales workflow/);
 const saleState=async()=> (await db.query("select sale_state from inventory_sale_states() where snake_id='M01'")).rows[0].sale_state;
 assert.equal(await saleState(),'available');
 await db.query("update specimen_listings set published=false where slug='m01'");assert.equal(await saleState(),'normal');
 await db.query("update specimen_listings set published=true,sale_status='display' where slug='m01'");assert.equal(await saleState(),'normal');
 await db.query("update specimen_listings set sale_status='available' where slug='m01'");assert.equal(await saleState(),'available');
 const action=(id,name,until=null,amount=null)=>db.query('select manage_specimen_sale($1,$2,$3,$4,$5)',[id,name,'测试记录',until,amount]);
 await action(inquiries[0].id,'reserve','2099-01-01',3500);
 await assert.rejects(db.query("select delete_specimen_listing('11111111-1111-4111-8111-111111111111')"),/有效预留/);
 await assert.rejects(action(inquiries[1].id,'reserve','2099-01-01',3500),/not available/);
 await assert.rejects(action(inquiries[0].id,'complete'),/Invalid transition/);
 await action(inquiries[0].id,'paid');await action(inquiries[0].id,'deliver');await action(inquiries[0].id,'complete');
 assert.equal((await db.query(`select sale_status from specimen_listings where slug='m01'`)).rows[0].sale_status,'sold');
 const event=(await db.query(`select record_breeding_event(null,null,'M01','M02','2026-01-01','paired','真实记录') as id`)).rows[0].id;
 const clutch=(await db.query(`select record_clutch(null,$1,'CL-1','2026-02-01',3,2,1,'hatched') as id`,[event])).rows[0].id;
 await db.query(`select register_hatchling($1,'M03','U','2026-03-01','系列','待确认','owner')`,[clutch]);
 await assert.rejects(db.query(`select register_hatchling($1,'M04','U','2026-03-01','系列','待确认','owner')`,[clutch]),/already registered/);
 await db.exec('reset role');const hatch=(await db.query(`select * from snakes where id='M03'`)).rows[0];assert.equal(hatch.dam_id,'M01');assert.equal(hatch.sire_id,'M02');assert.equal(hatch.origin,'produced');
 assert.equal(hatch.inventory_library,'nursery');
 await db.exec('set role authenticated');
 await assert.rejects(db.query("update snakes set inventory_library='stock' where id='M03'"),/transfer workflow/);
 await db.query("select transfer_inventory_animal('M03','stock')");
 await db.exec('reset role');
 assert.equal((await db.query("select inventory_library from snakes where id='M03'")).rows[0].inventory_library,'stock');
 assert.equal((await db.query("select count(*) from snakes where id='M03'")).rows[0].count,1);
 assert.equal((await db.query("select count(*) from inventory_transfers where individual_id='M03'")).rows[0].count,1);
 await db.exec("update profiles set role='viewer';set role authenticated");
 await assert.rejects(db.query("select transfer_inventory_animal('M03','nursery')"),/Not authorized/);
 await db.exec("reset role;update profiles set role='admin'");
 assert.equal((await db.query("select status from snakes where id='M01'")).rows[0].status,'sold');
 await assert.rejects(db.query("update snakes set status='active' where id='M01'"),/separate correction workflow/);
 const cost=(await db.query(`select * from snake_acquisition_costs where snake_id='M01'`)).rows[0];assert.equal(Number(cost.amount),12345);
 await db.query(`insert into investment_expenses(category,amount,owner_id,acquisition_id) values('population',12345,auth.uid(),$1)`,[cost.id]);
 await assert.rejects(db.query(`insert into investment_expenses(category,amount,owner_id,acquisition_id) values('population',12345,auth.uid(),$1)`,[cost.id]),/duplicate key/);
 await assert.rejects(db.query(`insert into investment_expenses(category,amount,owner_id,acquisition_id) values('equipment',1,auth.uid(),$1)`,[cost.id]),/population category/);
 await db.exec(`insert into snakes(id,price,status,sex) values('Y99',777,'active','U');delete from snakes where id='Y99';`);
 const retained=(await db.query(`select * from snake_acquisition_costs where individual_id='Y99'`)).rows[0];assert.equal(retained.snake_id,null);assert.equal(Number(retained.amount),777);
 await db.exec(`insert into route_nodes values('node-1',100,200);set role authenticated;`);
 await db.query(`select move_route_node('node-1',110,210,100,200)`);
 await assert.rejects(db.query(`select move_route_node('node-1',120,220,100,200)`),/another session/);
 await db.query(`select move_route_node('node-1',100,200,110,210)`);
 await db.query("select delete_specimen_listing('11111111-1111-4111-8111-111111111111')");
 assert.equal((await db.query('select public_catalog() as data')).rows[0].data.items.length,0);
 assert.equal((await db.query("select count(*) from purchase_inquiries")).rows[0].count,2);
 assert.equal((await db.query("select count(*) from snakes where id='M01'")).rows[0].count,1);
 await assert.rejects(db.query("update specimen_listings set published=true where slug='m01'"),/deleted_listing_is_private/);
 await db.query("update specimen_listings set deleted_at=null,published=true where slug='m01'");
 assert.equal((await db.query('select public_catalog() as data')).rows[0].data.items.length,1);

 await db.exec("reset role;insert into annual_breeding_plans(id,female_snake_id,male_snake_id,review_status,project_name,plan_year,status,expected_pairing_date,expected_laying_date,expected_hatching_date) values(200,'M01','M02','approved','测试繁育',2026,'planned','2026-01-01','2026-02-01','2026-03-01')");
 await assert.rejects(db.query("update annual_breeding_plans set expected_hatching_date='2025-01-01' where id=200"),/breeding_expected_dates_order/);
 await db.exec('set role authenticated');
 const actualEvent=(await db.query("select record_breeding_event(null,200,'M01','M02','2026-01-01','successful','真实交配') as id")).rows[0].id;
 const clutchParams=[null,actualEvent,'CAL-200','2026-02-01',3,3,2,'hatched','2026-03-01','2026-03-03','2026-03-02'];
 const callClutch=values=>db.query('select record_clutch_dates($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) as id',values);
 await assert.rejects(callClutch([...clutchParams.slice(0,8),'2026-01-01',null,'2026-03-02']),/日期/);
 const actualClutch=(await callClutch(clutchParams)).rows[0].id;
 await assert.rejects(db.query("select record_breeding_event($1,200,'M01','M02','2026-04-01','successful','修改日期')",[actualEvent]),/交配日期不能晚于/);
 const calendar=(await db.query('select breeding_calendar() as data')).rows[0].data;
 assert.equal(calendar.length,1);assert.equal(calendar[0].events[0].status,'successful');assert.equal(calendar[0].clutches[0].hatch_start,'2026-03-01');assert.equal(calendar[0].clutches[0].hatch_end,'2026-03-03');
 await db.exec('reset role');assert.equal((await db.query('select count(*) from clutches where id=$1',[actualClutch])).rows[0].count,1);
 await db.exec('set role anon');await assert.rejects(db.query('select breeding_calendar()'),/permission denied/);

 await db.exec(`reset role;
 create table public.snake_measurements(id uuid primary key default gen_random_uuid(),snake_id text,measured_at date,weight_g numeric,length_cm numeric,feeding_status text,condition_note text,created_at timestamptz default now());
 insert into specimen_media(listing_id,storage_path,caption) values('11111111-1111-4111-8111-111111111111','11111111-1111-4111-8111-111111111111/old.webp','原有照片');`);
 await db.exec(fs.readFileSync('supabase/migrations/026_public_media_selection.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/027_growth_and_batch_registration.sql','utf8'));
 assert.equal((await db.query("select is_public from specimen_media where caption='原有照片'")).rows[0].is_public,true);
 await db.exec(`insert into specimen_media(listing_id,storage_path,caption) values('11111111-1111-4111-8111-111111111111','11111111-1111-4111-8111-111111111111/private.webp','内部照片');
 update snakes set birth_date='2025-06-01' where id='M01';insert into genes values('g1','测试基因');insert into snake_genes values('M01','g1','possible_het',0.5);
 set role anon;`);
 let filtered=(await db.query("select public_catalog_v2(p_year=>2025,p_gene=>'g1',p_gene_state=>'possible_het') as data")).rows[0].data;
 assert.equal(filtered.total,1);assert.equal(filtered.items[0].photos.length,1);assert.equal(filtered.items[0].photos[0].caption,'原有照片');
 assert.equal((await db.query("select public_catalog_v2(p_gene=>'g1',p_gene_state=>'het') as data")).rows[0].data.total,0);
 assert.equal((await db.query("select is_published_specimen_media('11111111-1111-4111-8111-111111111111/private.webp') as allowed")).rows[0].allowed,false);
 await assert.rejects(db.query("select retain_inventory_animal('M03','test')"),/permission denied/);
 await db.exec("reset role;update specimen_listings set birth_precision='unknown' where slug='m01';set role anon");
 assert.equal((await db.query("select public_catalog_v2(p_year=>2025) as data")).rows[0].data.total,0);
 assert.deepEqual((await db.query('select public_catalog_v2() as data')).rows[0].data.years,[]);
 await db.exec('reset role;set role authenticated');
 const request='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
 const batchRows=[{id:'BATCH01',sex:'U',birth:'2026-03-01',series:'系列',gene_text:'待确认'},{id:'BATCH02',sex:'F',birth:'2026-03-02',series:'系列',gene_text:'人工确认描述'}];
 const batch=(rows=batchRows,key=request)=>db.query('select register_hatchlings_batch($1,$2,$3,$4) as data',[key,actualClutch,JSON.stringify(rows),'owner']);
 await assert.rejects(batch([{...batchRows[0]},{...batchRows[1],id:'M01'}]),/第 2 行/);
 assert.equal((await db.query("select count(*) from snakes where id='BATCH01'")).rows[0].count,0);
 assert.deepEqual((await batch()).rows[0].data,['BATCH01','BATCH02']);
 assert.deepEqual((await batch()).rows[0].data,['BATCH01','BATCH02']);
 await assert.rejects(batch([{...batchRows[0],id:'OTHER'}]),/conflict/);
 await assert.rejects(batch([{...batchRows[0],id:'EXCESS'}],'cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/超过/);
 await db.query("select retain_inventory_animal('BATCH01','保留观察结果，基因仍待确认')");
 assert.equal((await db.query("select count(*) from snakes where id='BATCH01'")).rows[0].count,1);
 assert.equal((await db.query("select assessment from inventory_transfers where individual_id='BATCH01'")).rows[0].assessment,'保留观察结果，基因仍待确认');
 await db.exec("reset role;update profiles set role='viewer';set role authenticated");
 await assert.rejects(batch(),/Not authorized/);
 await assert.rejects(db.query("select retain_inventory_animal('BATCH02','test')"),/Not authorized/);
 }finally{await db.close();}
});
