-- Suoha Hognose Breeding OS
-- 005: Versioned planning and auditable AI analysis
-- Safe to run after the existing private-app/RLS schema. It is additive and idempotent.

begin;

create table if not exists public.planning_scenarios (
  id bigint generated by default as identity primary key,
  name text not null,
  scenario_type text not null default 'manual_draft'
    check (scenario_type in ('baseline','manual_draft','ai_draft','archived')),
  status text not null default 'draft'
    check (status in ('draft','accepted','rejected','superseded','archived')),
  planning_year integer check (planning_year between 2000 and 2200),
  as_of_at timestamptz not null default now(),
  assumptions jsonb not null default '[]'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  superseded_by bigint references public.planning_scenarios(id) on delete set null,
  notes text
);

alter table public.annual_breeding_plans add column if not exists scenario_id bigint;
do $$ begin
  if not exists (select 1 from pg_constraint where conname='annual_breeding_plans_scenario_id_fkey' and conrelid='public.annual_breeding_plans'::regclass) then
    alter table public.annual_breeding_plans add constraint annual_breeding_plans_scenario_id_fkey
      foreign key (scenario_id) references public.planning_scenarios(id) on delete set null;
  end if;
end $$;

insert into public.planning_scenarios (name,scenario_type,status,as_of_at,notes)
select '当前正式规划基线','baseline','accepted',now(),'正式规划基线；已有年度计划会归入此场景。'
where not exists (select 1 from public.planning_scenarios where scenario_type='baseline' and status='accepted');

update public.annual_breeding_plans set scenario_id=(
  select id from public.planning_scenarios where scenario_type='baseline' and status='accepted' order by id limit 1
) where scenario_id is null;

create table if not exists public.ai_prompt_templates (
  id bigint generated by default as identity primary key,
  template_key text not null,
  version integer not null check (version > 0),
  name text not null,
  analysis_type text not null check (analysis_type in ('pairing','annual_plan','investment','strategy_score')),
  system_prompt text not null,
  response_schema_version text not null default 'v2',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(template_key,version)
);

create table if not exists public.analysis_runs (
  id bigint generated by default as identity primary key,
  analysis_type text not null check (analysis_type in ('pairing','annual_plan','investment','strategy_score')),
  status text not null default 'queued' check (status in ('queued','running','succeeded','failed','expired')),
  as_of_at timestamptz not null,
  source_snapshot jsonb not null,
  source_hash text,
  model_provider text not null default 'deepseek',
  model_name text,
  model_version text,
  prompt_template_id bigint references public.ai_prompt_templates(id) on delete set null,
  prompt_version integer,
  response_schema_version text not null default 'v2',
  request_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb,
  error_message text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.ai_recommendations (
  id bigint generated by default as identity primary key,
  analysis_run_id bigint not null references public.analysis_runs(id) on delete cascade,
  recommendation_type text not null check (recommendation_type in ('pairing','annual_plan','investment','route','strategy_score','warning')),
  status text not null default 'proposed' check (status in ('proposed','accepted','rejected','expired','applied')),
  title text not null,
  summary text,
  confidence numeric(5,4) check (confidence between 0 and 1),
  priority_score smallint check (priority_score between 0 and 100),
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  target_refs jsonb not null default '[]'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  assumptions jsonb not null default '[]'::jsonb,
  risk_flags jsonb not null default '[]'::jsonb,
  missing_inputs jsonb not null default '[]'::jsonb,
  proposal_payload jsonb not null default '{}'::jsonb,
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_until is null or valid_until > valid_from)
);

create index if not exists idx_annual_plans_scenario on public.annual_breeding_plans(scenario_id);
create index if not exists idx_ai_prompt_templates_active on public.ai_prompt_templates(template_key,is_active,version desc);
create index if not exists idx_analysis_runs_type_created on public.analysis_runs(analysis_type,created_at desc);
create index if not exists idx_ai_recommendations_status_type on public.ai_recommendations(status,recommendation_type);

create or replace function public.touch_ai_decision_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists trg_planning_scenarios_updated_at on public.planning_scenarios;
create trigger trg_planning_scenarios_updated_at before update on public.planning_scenarios for each row execute function public.touch_ai_decision_updated_at();
drop trigger if exists trg_ai_prompt_templates_updated_at on public.ai_prompt_templates;
create trigger trg_ai_prompt_templates_updated_at before update on public.ai_prompt_templates for each row execute function public.touch_ai_decision_updated_at();
drop trigger if exists trg_ai_recommendations_updated_at on public.ai_recommendations;
create trigger trg_ai_recommendations_updated_at before update on public.ai_recommendations for each row execute function public.touch_ai_decision_updated_at();

alter table public.planning_scenarios enable row level security;
alter table public.ai_prompt_templates enable row level security;
alter table public.analysis_runs enable row level security;
alter table public.ai_recommendations enable row level security;
drop policy if exists planning_scenarios_authenticated_read on public.planning_scenarios;
create policy planning_scenarios_authenticated_read on public.planning_scenarios for select to authenticated using (true);
drop policy if exists planning_scenarios_editor_write on public.planning_scenarios;
create policy planning_scenarios_editor_write on public.planning_scenarios for all to authenticated using (public.can_edit_app()) with check (public.can_edit_app());
drop policy if exists ai_prompt_templates_authenticated_read on public.ai_prompt_templates;
create policy ai_prompt_templates_authenticated_read on public.ai_prompt_templates for select to authenticated using (true);
drop policy if exists ai_prompt_templates_admin_write on public.ai_prompt_templates;
create policy ai_prompt_templates_admin_write on public.ai_prompt_templates for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
drop policy if exists analysis_runs_authenticated_read on public.analysis_runs;
create policy analysis_runs_authenticated_read on public.analysis_runs for select to authenticated using (true);
drop policy if exists analysis_runs_editor_write on public.analysis_runs;
create policy analysis_runs_editor_write on public.analysis_runs for all to authenticated using (public.can_edit_app()) with check (public.can_edit_app());
drop policy if exists ai_recommendations_authenticated_read on public.ai_recommendations;
create policy ai_recommendations_authenticated_read on public.ai_recommendations for select to authenticated using (true);
drop policy if exists ai_recommendations_editor_write on public.ai_recommendations;
create policy ai_recommendations_editor_write on public.ai_recommendations for all to authenticated using (public.can_edit_app()) with check (public.can_edit_app());

insert into public.ai_prompt_templates(template_key,version,name,analysis_type,system_prompt,response_schema_version,is_active) values
('pairing_lab',2,'配对实验室 · 严格结构化建议','pairing',$$你是西部猪鼻蛇繁殖运营分析助手。只能使用用户输入 JSON 中的事实；不得编造蛇、基因、血缘、市场价格、可购性、繁殖事件或后代概率。snake_genes/atomic_genes 才是遗传事实，gene_text 仅供阅读；possible_het 不得当作 het；组合 morph 不得写入原子基因。计划不等于实际配种。
只输出一个合法 JSON 对象，禁止 Markdown、代码块、解释性前后缀。根对象只能含 recommendations。recommendations 必须是 0–8 项数组；每项必须且只能含 title、summary、confidence、priority_score、target_refs、evidence_refs、assumptions、risk_flags、missing_inputs、proposal_payload。title 为 1–80 字符，summary 为 1–500 字符，confidence 为 0–1 数字，priority_score 为 0–100 整数；所有 *_refs 与说明字段均为最多 12 项的字符串数组。
proposal_payload.action 只能是 create_annual_plan 或 none。仅当输入中明确包含对应真实父母 ID 时，create_annual_plan 才可填写 plan_year、female_snake_id、male_snake_id、priority(A/B/R/C/G)、project_name、goal、mode、planned_clutches(0–20)；否则 action 必须是 none。$$,'v2',true),
('annual_plan',2,'年度规划 · 严格结构化草案','annual_plan',$$你是西部猪鼻蛇繁殖运营分析助手。只能依据输入的真实种群、已接受正式计划、路线和成熟约束生成草案；不得编造市场、生物学保证、真实繁殖结果或不存在的 ID。草案不是执行记录；虚拟路线节点必须写入 assumptions 或 risk_flags。
只输出一个合法 JSON 对象，禁止 Markdown、代码块、解释性前后缀。根对象只能含 recommendations。recommendations 必须是 0–12 项数组；每项必须且只能含 title、summary、confidence、priority_score、target_refs、evidence_refs、assumptions、risk_flags、missing_inputs、proposal_payload。title 为 1–80 字符，summary 为 1–500 字符，confidence 为 0–1 数字，priority_score 为 0–100 整数；所有数组最多 12 个字符串。
proposal_payload.action 只能是 create_annual_plan 或 none。create_annual_plan 仅可引用输入中存在的父母/路线 ID，且必须含 plan_year、female_snake_id、male_snake_id、priority(A/B/R/C/G)、project_name、goal、mode、planned_clutches(0–20)；无法满足时 action 必须是 none。$$,'v2',true),
('investment',2,'投资缺口 · 严格结构化建议','investment',$$你是西部猪鼻蛇繁殖运营分析助手。只分析输入中的内部种群、路线、已录入投资和结构缺口。未提供外部市场数据时，不得推测价格、稀缺度、可购性或回报。不得把建议描述为已完成购买。
只输出一个合法 JSON 对象，禁止 Markdown、代码块、解释性前后缀。根对象只可含 recommendations。recommendations 必须是 0–8 项数组；每项必须且只能含 title、summary、confidence、priority_score、target_refs、evidence_refs、assumptions、risk_flags、missing_inputs、proposal_payload。title 为 1–80 字符，summary 为 1–500 字符，confidence 为 0–1 数字，priority_score 为 0–100 整数；所有数组最多 12 个字符串。proposal_payload 只能包含 action:'none'，以及可选 target_sex、target_gene_ids、review_after（均不可声称外部事实）。$$,'v2',true),
('strategy_score',2,'战略评分 · 严格结构化建议','strategy_score',$$你是西部猪鼻蛇繁殖运营分析助手。评分只表示输入快照与当前目标下的规划价值，不代表市场价格、生物学质量或繁殖保证。只输出合法 JSON，不输出 Markdown。响应结构与 pairing_lab 相同；proposal_payload.action 必须为 none。$$,'v2',true)
on conflict(template_key,version) do update set name=excluded.name,system_prompt=excluded.system_prompt,response_schema_version=excluded.response_schema_version,is_active=excluded.is_active;

-- Keep only the newest prompt active for each analysis workflow.
update public.ai_prompt_templates set is_active=false where version < 2 and template_key in ('pairing_lab','annual_plan','investment','strategy_score');

commit;
