-- Suoha Hognose Breeding OS
-- 006: Persistent AI follow-up conversations
-- Run after 005_ai_decision_layer.sql. Additive and idempotent.

begin;

create table if not exists public.ai_conversations (
  id bigint generated by default as identity primary key,
  analysis_run_id bigint not null unique references public.analysis_runs(id) on delete cascade,
  analysis_type text not null check (analysis_type in ('pairing','annual_plan','investment','strategy_score')),
  title text,
  model_name text,
  prompt_template_id bigint references public.ai_prompt_templates(id) on delete set null,
  prompt_version integer,
  source_snapshot jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_conversation_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.ai_conversations(id) on delete cascade,
  role text not null check (role in ('user','assistant','system')),
  content text not null check (char_length(content) between 1 and 6000),
  structured_payload jsonb,
  model_name text,
  prompt_version integer,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_conversation_messages_conversation_created
  on public.ai_conversation_messages(conversation_id, created_at);

create or replace function public.touch_ai_conversation_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end;
$$;

drop trigger if exists trg_ai_conversations_updated_at on public.ai_conversations;
create trigger trg_ai_conversations_updated_at before update on public.ai_conversations
  for each row execute function public.touch_ai_conversation_updated_at();

alter table public.ai_conversations enable row level security;
alter table public.ai_conversation_messages enable row level security;

drop policy if exists ai_conversations_authenticated_read on public.ai_conversations;
create policy ai_conversations_authenticated_read on public.ai_conversations
  for select to authenticated using (true);
drop policy if exists ai_conversations_editor_write on public.ai_conversations;
create policy ai_conversations_editor_write on public.ai_conversations
  for all to authenticated using (public.can_edit_app()) with check (public.can_edit_app());

drop policy if exists ai_conversation_messages_authenticated_read on public.ai_conversation_messages;
create policy ai_conversation_messages_authenticated_read on public.ai_conversation_messages
  for select to authenticated using (true);
drop policy if exists ai_conversation_messages_editor_write on public.ai_conversation_messages;
create policy ai_conversation_messages_editor_write on public.ai_conversation_messages
  for all to authenticated using (public.can_edit_app()) with check (public.can_edit_app());

commit;
